name: Lint & reformat

on:
  pull_request:
    branches: ["master"]

  workflow_dispatch:

jobs:
  reformat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt
      - name: Install pip packages
        run: python3 -m pip install --upgrade autopep8 pycodestyle eradicate
      - name: Run autopep8
        run: autopep8 --in-place -aa -r .
      - name: Remove commented out code
        run: eradicate --in-place ./**/*.py
      - name: Push back to repo
        uses: actions-go/push@v1
        with:
          author-email: github-actions[bot]@users.noreply.github.com
          author-name: Reformat action
          create-commit: true
          commit-message: "Reformatted code and removed commented-out code"
  lint:
    runs-on: ubuntu-latest
    needs: reformat
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt
      - name: Install pip packages
        run: python3 -m pip install --upgrade pycodestyle
      - name: Run pycodestyle
        run: pycodestyle --show-source --show-pep8 ./**/*.py
